"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/q7i2Dd497wN
 */
import { Input } from "@/components/ui/input";
import Link from "next/link";
import { Button } from "@/components/ui/button";

import { useState } from "react";
import NextImage from "next/image";

export function OGInput() {
  const [value, setValue] = useState<string>("");
  const [query, setQuery] = useState<string>(value);

  const [imageLoading, setImageLoading] = useState<boolean>(false);

  const url = `/clippify?text=${encodeURIComponent(query)}`;
  const fullURL = `https://og.lambdaops.com${url}`;

  return (
    <div className="space-y-2">
      <Input
        className="border border-zinc-200 dark:border-zinc-700 rounded-lg p-2 w-full"
        placeholder="prompt me"
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            setQuery(value);
          }
        }}
        onBlur={(e) => {
          setQuery(e.target.value);
        }}
        onChange={(e) => {
          setValue(e.target.value);
        }}
        type="text"
        value={value}
      />

      <div className="aspect-w-16 aspect-h-9">
        {/* eslint-disable-next-line @next/next/no-img-element*/}
        <img
          alt={query}
          className="object-cover rounded-lg"
          height={630}
          src={value !== query || imageLoading ? "/loading" : url}
          width={1200}
          onLoadStart={() => {
            setImageLoading(true);
          }}
          onLoad={() => {
            setImageLoading(false);
          }}
        />
      </div>
      <div className="flex items-center space-x-2">
        <Link
          className="underline text-zinc-600 dark:text-zinc-300 hover:text-zinc-500 dark:hover:text-zinc-400"
          href={fullURL}
        >
          {fullURL.slice(0, 50)}
        </Link>
        <Button
          variant="ghost"
          onClick={() => {
            navigator.clipboard.writeText(fullURL);
          }}
        >
          <svg
            className=" w-5 h-5 text-zinc-600 dark:text-zinc-300"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 0 24 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <rect height="14" rx="2" ry="2" width="14" x="8" y="8" />
            <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
          </svg>
        </Button>
      </div>
    </div>
  );
}
