export const emojis: Record<string, string> = {
  // "🆗": "ok",
  "🔞": "18+",
  "🤏": "pinching hand",
  "🤌": "pinched fingers",
  "🦾": "mechanical arm",
  "🦿": "mechanical leg",
  "🦻": "ear with hearing aid",
  "🧏": "deaf person",
  "🧍": "person standing",
  "🧎": "person kneeling",
  "🧑‍🤝‍🧑": "people holding hands",
  "👨‍❤️‍👨": "couple with heart: man, man",
  "👩‍❤️‍👩": "couple with heart: woman, woman",
  "💏": "kiss",
  "👩‍❤️‍💋‍👨": "kiss: woman, man",
  "👨‍❤️‍💋‍👨": "kiss: man, man",
  "👩‍❤️‍💋‍👩": "kiss: woman, woman",
  "💑": "couple with heart",
  "👩‍❤️‍👨": "couple with heart: woman, man",
  "👪": "family",
  "👨‍👩‍👦": "family: man, woman, boy",
  "👨‍👩‍👧": "family: man, woman, girl",
  "👨‍👩‍👧‍👦": "family: man, woman, girl, boy",
  "👨‍👩‍👦‍👦": "family: man, woman, boy, boy",
  "👨‍👩‍👧‍👧": "family: man, woman, girl, girl",
  "👨‍👨‍👦": "family: man, man, boy",
  "👨‍👨‍👧": "family: man, man, girl",
  "👨‍👨‍👧‍👦": "family: man, man, girl, boy",
  "👨‍👨‍👦‍👦": "family: man, man, boy, boy",
  "👨‍👨‍👧‍👧": "family: man, man, girl, girl",
  "👩‍👩‍👦": "family: woman, woman, boy",
  "👩‍👩‍👧": "family: woman, woman, girl",
  "👩‍👩‍👧‍👦": "family: woman, woman, girl, boy",
  "👩‍👩‍👦‍👦": "family: woman, woman, boy, boy",
  "👩‍👩‍👧‍👧": "family: woman, woman, girl, girl",
  "👨‍👦": "family: man, boy",
  "👨‍👦‍👦": "family: man, boy, boy",
  "👨‍👧": "family: man, girl",
  "👨‍👧‍👦": "family: man, girl, boy",
  "👨‍👧‍👧": "family: man, girl, girl",
  "👩‍👦": "family: woman, boy",
  "👩‍👦‍👦": "family: woman, boy, boy",
  "👩‍👧": "family: woman, girl",
  "👩‍👧‍👦": "family: woman, girl, boy",
  "👩‍👧‍👧": "family: woman, girl, girl",
  "🦧": "orangutan",
  "🦮": "guide dog",
  "🐕‍🦺": "service dog",
  "🦥": "sloth",
  "🦦": "otter",
  "🦨": "skunk",
  "🦩": "flamingo",
  "🧄": "garlic",
  "🧅": "onion",
  "🧇": "waffle",
  "🧆": "falafel",
  "🧈": "butter",
  "🦪": "oyster",
  "🧃": "beverage box",
  "🧉": "mate",
  "🧊": "ice cube",
  "🛕": "hindu temple",
  "🦫": "beaver",
  "🪀": "yo-yo",
  "🪁": "kite",
  "🪂": "parachute",
  "🪐": "ringed planet",
  "🫀": "anatomical heart",
  "🫁": "lungs",
  "🦷": "tooth",
  "🦴": "bone",
  "👨‍🦲": "bald man",
  "👩‍🦲": "bald woman",
  "🦸": "superhero",
  "🦹": "supervillain",
  "🦵": "leg",
  "🦶": "foot",
  "🦯": "white cane",
  "🦽": "manual wheelchair",
  "🦼": "motorized wheelchair",
  "🪑": "chair",
  "🪒": "razor",
  "🪓": "axe",
  "🪔": "diya lamp",
  "🪕": "banjo",
  "🪖": "military helmet",
  "🪗": "accordion",
  "🪘": "long drum",
  "🪙": "coin",
  "🪚": "saw",
  "🪛": "screwdriver",
  "🪜": "ladder",
  "🪝": "hook",
  "🪞": "mirror",
  "🪟": "window",
  "🪠": "plunger",
  "🪡": "sewing needle",
  "🪢": "knot",
  "🪣": "bucket",
  "🪤": "mouse trap",
  "🪥": "toothbrush",
  "🪦": "headstone",
  "🪧": "placard",
  "🤓": "nerd",
  "😎": "sunglasses",
  "🤩": "star eyes",
  "🤔": "thinking",
  "🤯": "mind blown",
  "😳": "flushed",
  "😱": "screaming",
  "😴": "sleeping",
  "😵": "dizzy",
  "🤢": "nauseated",
  // "🤮": "vomiting",
  "🤧": "sneezing",
  "🥵": "hot",
  "🥶": "cold",
  "🥴": "woozy",
  "😭": "crying",
  "😓": "sweating",
  "🤤": "drooling",
  "🤑": "money mouth",
  "🤠": "cowboy",
  "😈": "smiling devil",
  "👿": "angry devil",
  "👹": "ogre",
  "👺": "goblin",
  "💀": "skull",
  "👻": "ghost",
  "👽": "alien",
  "🤖": "robot",
  "😺": "grinning cat",
  "😸": "grinning cat with smiling eyes",
  "😹": "cat with tears of joy",
  "😻": "smiling cat with heart-eyes",
  "😼": "cat with wry smile",
  "😽": "kissing cat",
  "🙀": "weary cat",
  "😿": "crying cat",
  "😾": "pouting cat",
  "🙈": "see-no-evil monkey",
  "🙉": "hear-no-evil monkey",
  "🙊": "speak-no-evil monkey",
  "💋": "kiss mark",
  "💌": "love letter",
  "💘": "heart with arrow",
  "💝": "heart with ribbon",
  "💖": "sparkling heart",
  "💗": "growing heart",
  "💓": "beating heart",
  "💞": "revolving hearts",
  "💕": "two hearts",
  "💟": "heart decoration",
  "❣️": "heart exclamation",
  "💔": "broken heart",
  "❤️": "red heart",
  "🧡": "orange heart",
  "💛": "yellow heart",
  "💚": "green heart",
  "💙": "blue heart",
  "💜": "purple heart",
  "🖤": "black heart",
  "💯": "hundred points",
  "💢": "anger symbol",
  "💥": "collision",
  "💫": "dizzy",
  "💦": "sweat droplets",
  "💨": "dashing away",
  "🕳️": "hole",
  "💣": "bomb",
  "💬": "speech balloon",
  "😀": "grinning face",
  "😂": "tears of joy",
  "👍": "thumbs up",
  "🚀": "rocket",
  "🐱": "cat",
  "🐶": "dog",
  "🍕": "pizza",
  "🍔": "hamburger",
  "🍣": "sushi",
  "🍦": "ice cream",
  "👋": "hello",
  "🦕": "dinosaur",
  "🦖": "T-Rex",
  "🦈": "shark",
  "🌈": "rainbow",
  "🌊": "ocean wave",
  "🎉": "party",
  "🎊": "celebration",
  "🎁": "gift",
  "🎈": "balloon",
  "🎀": "ribbon",
  "🎄": "Christmas tree",
  "🎃": "pumpkin",
  "👾": "space invader",
  "👑": "crown",
  "🎩": "top hat",
  "💩": "poop",
  "🍺": "beer",
  "🍷": "wine",
  "🔥": "fire",
  "🌟": "star",
  "💡": "idea",
  "📚": "book",
  "🎵": "music",
  "🎮": "video game",
  "⚽": "soccer",
  "🚲": "bicycle",
  "🕒": "clock",
  "🎭": "drama",
  "🛒": "shopping cart",
  "💻": "laptop",
  "🎥": "movie",
  "🍿": "popcorn",
  "🛏️": "bed",
  "🚗": "car",
  "✈️": "airplane",
  "🏠": "house",
  "🏝️": "island",
  "🌆": "cityscape",
  "🏰": "castle",
  "🗽": "statue of liberty",
  "🗺️": "world map",
  "🎢": "roller coaster",
  "🎡": "ferris wheel",
  "🎠": "carousel horse",
  "🎪": "circus tent",
  "🎬": "clapper board",
  "🎤": "microphone",
  "🎧": "headphone",
  "🎹": "musical keyboard",
  "🎺": "trumpet",
  "🎷": "saxophone",
  "🥁": "drum",
  "🎸": "guitar",
  "🎻": "violin",
  // "🎲": "die",
  "🎯": "bullseye",
  "🎳": "bowling",
  "🎰": "slot machine",
  "🎱": "billiards",
  "🧪": "test tube",
  "🧬": "DNA",
  "🧮": "abacus",
  "🧲": "magnet",
  "🧸": "teddy bear",
  "🧩": "puzzle piece",
  "🧨": "firecracker",
  "🧧": "red envelope",
  "🧦": "socks",
  "🧤": "gloves",
  "🧣": "scarf",
  "🧥": "coat",
  "🧢": "cap",
  "🧵": "thread",
  "🧶": "yarn",
  "🧴": "lotion",
  "🧷": "safety pin",
  "🧹": "broom",
  "🧺": "basket",
  "🧻": "toilet paper",
  "🧼": "soap",
  "🧽": "sponge",
  "🧯": "fire extinguisher",
  "🚬": "cigarette",
  "🚭": "no smoking",
  "🚰": "potable water",
  "🚱": "non-potable water",
  "🚳": "no bicycles",
  "🚷": "no pedestrians",
  "🚸": "children crossing",
  "🍆": "eggplant",
  "🍑": "peach",
  "🍌": "banana",
  "🍎": "apple",
  "🍏": "green apple",
  "🍊": "tangerine",
  "🍋": "lemon",
  "🍉": "watermelon",
  "🍇": "grapes",
  "🍓": "strawberry",
  "🍈": "melon",
  "🍒": "cherries",
  "🍍": "pineapple",
  "🍅": "tomato",
  "🐼": "panda",
  "🐻": "bear",
  "🐨": "koala",
  "🐯": "tiger",
  "☕️": "coffee",
  "🍵": "tea",
  "🍼": "baby bottle",
  "🍻": "clinking beer mugs",
};

